{
  "sksl": {
    "entrypoint": "liquid_distortion_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform float uTime;\nuniform vec2 uSize;\nuniform vec3 uColor1;\nuniform vec3 uColor2;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 uv = FLT_flutter_local_FlutterFragCoord() / uSize;\n    float distortion = sin((uv.x * 10.0) + uTime) * 0.0199999995529651641845703125;\n    distortion += (cos((uv.y * 8.0) + (uTime * 0.800000011920928955078125)) * 0.0199999995529651641845703125);\n    vec2 distortedUv = uv + vec2(distortion);\n    vec3 finalColor = mix(uColor1, uColor2, vec3(distortedUv.y + distortion));\n    fragColor = vec4(finalColor, 1.0);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uColor1",
        "rows": 3,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "uColor2",
        "rows": 3,
        "type": 10
      }
    ]
  }
}